### ISSUE TITLE
PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by bihor** [tollwerk/TYPO3-ext-tw_antibot#4]
#1: PHP Runtime Deprecation Notice: Non-static method Tollwerk\TwAntibot\Utility\Utility::settings() should not be called statically, assuming $this from incompatible context in /html/typo3/typo3conf/ext/tw_antibot/Classes/ViewHelpers/AbstractAntibotViewHelper.php line 56

Used version: 0.2.0 in TYPO3 6.2.x

**Comment by jkphl** [comment]
@bihor This was already fixed for quite some time but not part of a release yet. I just pushed out [release 0.2.1](https://github.com/tollwerk/TYPO3-ext-tw_antibot/releases/tag/v0.2.1) ... Thanks for reporting!
